spring:
  application:
    name: otp_rest_api_app
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
otp-settings:
  default-live-time: 300
token:
  signing:
    key: ${SECRET_KEY}
logging:
  file:
    path: ./logs
mail:
  host: ${SMTP_HOST}
  port: ${SMTP_PORT}
  username: ${EMAIL_USERNAME}
  password: ${EMAIL_PASSWORD}
  test-connection: false
  properties:
    health:
      mail:
        enabled: false
    mail:
      smtp:
        auth: true
        starttls:
          enabled: true
notification:
  smpp:
    host: ${SMPP_HOST}
    port: ${SMPP_PORT}
    system_id: ${SMPP_SYSTEM_ID}
    password: ${SMPP_PASSWORD}
    system_type: ${SMPP_SYSTEM_TYPE}
    source_addr: ${SMPP_SOURCE_ADDR}
  telegram:
    bot:
      token: ${TELEGRAM_TOKEN}
